-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: autopep8-wrapper
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: flake8
        args: ['--ignore=E501']
    -   id: pretty-format-json

